### ISSUE TITLE
Odd issue, can't resolve.

### ISSUE THREAD

**Issue by mingdc** [ahmadudin/electron-instaPy-GUI#47]
> Error: INFO [2018-03-02 03:45:08] [USERNAME] Session started - 2018-03-02 03:45:08
 WARNING [2018-03-02 03:45:08] [USERNAME] Sorry, Record Activity is not working on Windows. We're working to fix this soon!
 INFO [2018-03-02 03:45:40] [USERNAME] Logged in successfully!
 Traceback (most recent call last):
 File "quickstart.py", line 5, in <module>
 session.login()
 File "E:\USER\Desktop\InstaPy-master\instapy\instapy.py", line 271, in login
 self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
 File "E:\USER\Desktop\InstaPy-master\instapy\print_log_writer.py", line 11, in log_follower_num
 "return window._sharedData.""entry_data.ProfilePage[0]."
 File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script
 'args': converted_args})['value']
 File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
 self.error_handler.check_response(response)
 File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
 (Session info: chrome=64.0.3282.186)
 (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 6.1.7601 SP1 x86_64)
 
Complete newb, although trying to resolve this myself. If someone knows the exact issue please chip in, thankyou :)

**Comment by faizalshuriken** [comment]
Try this;

Go to InstaPy-master folder-->Select Scripts-->Then Right Click on 'Windows'-->Select Run As an Admin/Run With PowerShell-->Let it run-->when it's done,press enter to continue.

**Comment by emyabdel** [comment]
I have the same problem, i tried this but doesn't work. any other solution?
