### ISSUE TITLE
unsupported pickle protocol: 3 InstaPy ended

### ISSUE THREAD

**Issue by ferrufin0** [ahmadudin/electron-instaPy-GUI#67]
need help here please

`Error: INFO [2018-06-04 22:44:34] [jorgeferrufino] Session started - 2018-06-04 22:44:34 Traceback (most recent call last): File "quickstart.py", line 5, in <module> session.login() File "/Users/jorgeferrufino/Downloads/InstaPy/instapy/instapy.py", line 322, in login self.bypass_suspicious_attempt): File "/Users/jorgeferrufino/Downloads/InstaPy/instapy/login_util.py", line 107, in login_user .format(logfolder,username), 'rb')): File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1378, in load return Unpickler(file).load() File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load dispatch[key](self) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 886, in load_proto raise ValueError, "unsupported pickle protocol: %d" % proto ValueError: unsupported pickle protocol: 3`

**Comment by icyks** [comment]
Hello, 
So here's how you solve this problem
I think you are launching the quickstart with python 2.x
(to check it just type python and you will see the vestion)
So either you use python3 quickstart.py
Or you can use alias python=python3
and then use python quickstart.py

If you encounter some import problem, you can also try pip3 install . 
or pip3 install "MODULE_NAME"

;)
