### ISSUE TITLE
"npm start" and "npm run dist" fails (Raspberry Pi)

### ISSUE THREAD

**Issue by the-unknown** [ahmadudin/electron-instaPy-GUI#68]
Hey,

I want to complie the GUI on a raspberry pi.
When running "npm start" I get the folloing output:

> 
> InstaPyGUI@0.5.0 start /home/osmc/electron-instaPy-GUI
> electron .
>
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! InstaPyGUI@0.5.0 start: `electron .`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the InstaPyGUI@0.5.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

And when running "npm run dist"  I get the following error:

> InstaPyGUI@0.5.0 dist /home/osmc/electron-instaPy-GUI
> build
  • electron-builder version=20.15.3
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder-effective-config.yaml
**Error: Unsupported arch arm**
    at archFromString (/home/osmc/electron-instaPy-GUI/node_modules/builder-util/src/arch.ts:43:13)
    at computeArchToTargetNamesMap (/home/osmc/electron-instaPy-GUI/node_modules/electron-builder-lib/src/targets/targetFactory.ts:30:24)
    at /home/osmc/electron-instaPy-GUI/node_modules/electron-builder-lib/src/packager.ts:360:41
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/home/osmc/electron-instaPy-GUI/node_modules/electron-builder-lib/src/packager.ts:341:39)
    at /home/osmc/electron-instaPy-GUI/node_modules/electron-builder-lib/src/packager.ts:317:52
    at Generator.next (<anonymous>)
    at /home/osmc/electron-instaPy-GUI/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/osmc/electron-instaPy-GUI/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:171:20)
From previous event:
    at Packager._build (/home/osmc/electron-instaPy-GUI/node_modules/electron-builder-lib/src/packager.ts:294:133)
    at /home/osmc/electron-instaPy-GUI/node_modules/electron-builder-lib/src/packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (/home/osmc/electron-instaPy-GUI/node_modules/electron-builder-lib/src/packager.ts:248:14)
    at /home/osmc/electron-instaPy-GUI/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/osmc/electron-instaPy-GUI/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/home/osmc/electron-instaPy-GUI/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/home/osmc/electron-instaPy-GUI/node_modules/electron-builder/src/cli/cli.ts:46:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! InstaPyGUI@0.5.0 dist: `build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the InstaPyGUI@0.5.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osmc/.npm/_logs/2018-06-11T14_09_30_698Z-debug.log

Any ideas?

**Comment by andreescocard** [comment]
same here
