### ISSUE TITLE
Bot didn't working in GUI mode

### ISSUE THREAD

**Issue by overhode** [ahmadudin/electron-instaPy-GUI#76]
hi, if i use the console version of the program it works fine, if i install the gui i can't run it, if i press on run i get some error with this 

`File "quickstart.py", line 5, in <module> session.login() File "/home/kali/Downloads/InstaPy/instapy/instapy.py", line 350, in login self.bypass_suspicious_attempt): File "/home/kali/Downloads/InstaPy/instapy/login_util.py", line 100, in login_user update_activity() File "/home/kali/Downloads/InstaPy/instapy/util.py", line 196, in update_activity data['unfollows'], data['server_calls'], id)) sqlite3.OperationalError: attempt to write a readonly database`

and if i try to run the quickstart.py i get this error

```
ERROR [2018-09-01 16:24:45] [amazing_landscapes_worldwide]  Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-29-generic x86_64)
Traceback (most recent call last):
  File "/home/kali/Downloads/InstaPy/instapy/instapy.py", line 300, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-29-generic x86_64)

```

since i'm noob with the terminal, how can i fix this errors? i've searched and tried everything on the github issues

thanks in advance

**Comment by ahmadudin** [comment]
Yeah, this app is deprecated and so outdated compared to instapy. Just wait for an update.

**Comment by J-Arasti** [comment]
Hi, 
first of all,thanks @ahmadudin for your nice GUI, just Keep going man...!
as you have said in last comment, when is the lounch time of new version, i am so intrested in
as you know, GUI doesnt work with instapy bot
Good Luck
